[package]
name = "hooq"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
err-only = []
nightly = []

[dependencies]
proc-macro2 = { version = "1.0.95", features = ["span-locations"] }
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full", "extra-traits"] }

[build-dependencies]
rustc_version = "0.4.1"

[dev-dependencies]
clap = { version = "4.5.39", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
macrotest = "1.1.0"
tokio = { version = "1.45.1", features = ["full"] }
futures = "0.3.31"
